"$schema" = "https://schema.tauri.app/config/2"
productName = "reflux"
version = "0.1.0-alpha.1"
identifier = "dev.frays.reflux"

[build]
beforeDevCommand = "pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pnpm build"
frontendDist = "../build"

[app]
  [[app.windows]]
  title = "Reflux"
  width = 1400
  height = 800
  center = true

[bundle]
  active = true
  targets = "all"
  icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
  ]
  externalBin = [
    "bin/yt-dlp"
  ]

  [bundle.windows]
    allowDowngrades = true
    tsp = false

    [bundle.windows.webviewInstallMode]
      silent = true
      type = "downloadBootstrapper"

    [bundle.windows.wix] 
      version = "0.1.0.1"
